name: Docker Image CI

on:
  push:
    branches: "main"
    
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Debug Environment Variables
      run: |
        echo "CNAME: ${{secrets.CNAME}}"
        echo "DB_HOST: ${{secrets.DB_HOST}}"
        echo "DB_PORT: ${{secrets.DB_PORT}}"
        echo "DB_USERNAME: ${{secrets.DB_USERNAME}}"
        echo "DB_NAME: ${{secrets.DB_NAME}}"
        echo "DB_PASSWORD: ${{secrets.DB_PASSWORD}}"
        echo "JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}"
        echo "DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}"
      # Rest of the steps...
